### ISSUE TITLE
Crash with Base Metals [1.10.2]

### ISSUE THREAD

**Issue by teagan75** [MinecraftModDevelopmentMods/PowerAdvantage#30]
https://pastebin.com/fygktA9P

**Comment by thePalindrome** [comment]
Base Metals updated in an *incredibly* breaking way, so you need to go back one version
(BaseMetals_1.10.2-2.4.0.11 is what you want), you will also need to grab [mmd-orespawn](https://minecraft.curseforge.com/projects/mmd-orespawn) (the latest 10.2 seems to work on that)

**Comment by dshadowwolf** [comment]
2.5.0-beta1 series also works, but... yeah - the 2.4 series is what those were built against
